import { CardSet } from '../types'

export const TYPE = {
  PR: {
    text: 'ประชาสัมพันธ์',
    effect: '( เป็นกลาง ) >>> ( ฝั่งเรา )',
  },
  ATTACK: {
    text: 'โจมตี',
    effect: '( ฝั่งคู่แข่ง ) >>> ( เป็นกลาง )',
  },
}

interface CardList {
  [key: number]: CardSet
}

export const CARD = {
  0: {
    real: {
      name: 'แนะนำตัวต่อสาธารณะชน',
      type: TYPE.PR.text,
      audio: 1,
      visual: 1,
      text: 1,
      price: 50,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'แนะนำตัวต่อสาธารณะชน',
      type: TYPE.PR.text,
      audio: 1,
      visual: 1,
      text: 1,
      price: 25,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  1: {
    real: {
      name: 'โอ้ย ฉันทำงานหนักแหละ',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 5,
      price: 110,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'โอ้ย ฉันทำงานหนักแหละ',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 5,
      price: 55,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  2: {
    real: {
      name: 'ประกาศนโยบาย',
      type: TYPE.PR.text,
      audio: 7,
      visual: 2,
      text: 1,
      price: 140,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ประกาศนโยบาย',
      type: TYPE.PR.text,
      audio: 7,
      visual: 2,
      text: 1,
      price: 70,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  3: {
    real: {
      name: 'รักนะยัยประชาชน',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 4,
      price: 100,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'รักนะยัยประชาชน',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 4,
      price: 50,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  4: {
    real: {
      name: 'บริจาคการกุศล',
      type: TYPE.PR.text,
      audio: 0,
      visual: 20,
      text: 0,
      price: 220,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'บริจาคการกุศล',
      type: TYPE.PR.text,
      audio: 0,
      visual: 20,
      text: 0,
      price: 110,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  5: {
    real: {
      name: 'ไปบ้านเด็กกำพร้า',
      type: TYPE.PR.text,
      audio: 0,
      visual: 7,
      text: 0,
      price: 130,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ไปบ้านเด็กกำพร้า',
      type: TYPE.PR.text,
      audio: 0,
      visual: 7,
      text: 0,
      price: 65,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  6: {
    real: {
      name: 'รณรงค์เรื่องเพศหลากหลาย',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 14,
      price: 180,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'รณรงค์เรื่องเพศหลากหลาย',
      type: TYPE.PR.text,
      audio: 0,
      visual: 0,
      text: 14,
      price: 90,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  7: {
    real: {
      name: 'ลงพื้นที่ไปหาชาวบ้าน',
      type: TYPE.PR.text,
      audio: 15,
      visual: 10,
      text: 15,
      price: 320,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ลงพื้นที่ไปหาชาวบ้าน',
      type: TYPE.PR.text,
      audio: 15,
      visual: 10,
      text: 15,
      price: 160,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  8: {
    real: {
      name: 'ฉันจบเกียรตินิยม มหาลัยชั้นนำนะจ๊ะ!',
      type: TYPE.PR.text,
      audio: 12,
      visual: 0,
      text: 12,
      price: 160,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ฉันจบเกียรตินิยม มหาลัยชั้นนำนะจ๊ะ!',
      type: TYPE.PR.text,
      audio: 12,
      visual: 0,
      text: 12,
      price: 80,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  9: {
    real: {
      name: 'ร้องเพลงปลุกใจประชาชน',
      type: TYPE.PR.text,
      audio: 25,
      visual: 0,
      text: 0,
      price: 240,
      effect: TYPE.PR.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ร้องเพลงปลุกใจประชาชน',
      type: TYPE.PR.text,
      audio: 25,
      visual: 0,
      text: 0,
      price: 120,
      effect: TYPE.PR.effect,
      description: '',
      isReal: false,
    },
  },
  10: {
    real: {
      name: 'แอบปล่อยรูปหลุด',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 20,
      text: 0,
      price: 300,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'แอบปล่อยรูปหลุด',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 20,
      text: 0,
      price: 150,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  11: {
    real: {
      name: 'มันด่าประชาชน!!!',
      type: TYPE.ATTACK.text,
      audio: 8,
      visual: 0,
      text: 8,
      price: 140,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'มันด่าประชาชน!!!',
      type: TYPE.ATTACK.text,
      audio: 8,
      visual: 0,
      text: 8,
      price: 70,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  12: {
    real: {
      name: 'นโยบายเขาแย่',
      type: TYPE.ATTACK.text,
      audio: 10,
      visual: 0,
      text: 0,
      price: 150,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'นโยบายเขาแย่',
      type: TYPE.ATTACK.text,
      audio: 10,
      visual: 0,
      text: 0,
      price: 75,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  13: {
    real: {
      name: 'เธอ ซื้อ เสียง',
      type: TYPE.ATTACK.text,
      audio: 10,
      visual: 10,
      text: 15,
      price: 420,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'เธอ ซื้อ เสียง',
      type: TYPE.ATTACK.text,
      audio: 10,
      visual: 10,
      text: 15,
      price: 210,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  14: {
    real: {
      name: 'นางทำงานไม่เป็น',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 3,
      text: 2,
      price: 120,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'นางทำงานไม่เป็น',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 3,
      text: 2,
      price: 60,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  15: {
    real: {
      name: 'ลูกชายนางเป็นเด็กเกเร',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 0,
      text: 7,
      price: 130,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'ลูกชายนางเป็นเด็กเกเร',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 0,
      text: 7,
      price: 65,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  16: {
    real: {
      name: 'นางแอบล่าสัตว์สงวน',
      type: TYPE.ATTACK.text,
      audio: 20,
      visual: 0,
      text: 0,
      price: 200,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'นางแอบล่าสัตว์สงวน',
      type: TYPE.ATTACK.text,
      audio: 20,
      visual: 0,
      text: 0,
      price: 100,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  17: {
    real: {
      name: 'นางซื้อกระเป๋าจระเข้!',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 3,
      text: 0,
      price: 60,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'นางซื้อกระเป๋าจระเข้',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 3,
      text: 0,
      price: 30,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
  18: {
    real: {
      name: 'นางโพสต์บุลลี่เพื่อนค่า!!',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 0,
      text: 25,
      price: 240,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: true,
    },
    fake: {
      name: 'นางโพสต์บุลลี่เพื่อนค่า!',
      type: TYPE.ATTACK.text,
      audio: 0,
      visual: 0,
      text: 25,
      price: 120,
      effect: TYPE.ATTACK.effect,
      description: '',
      isReal: false,
    },
  },
} as CardList
