export const CHANNEL = {
  โซเชียลมีเดีย: {
    name: 'โซเชียลมีเดีย',
    audio: 1,
    visual: 1,
    text: 1,
    price: 500,
    baseFactor: 15,
  },
  ปากต่อปาก: {
    name: 'ปากต่อปาก',
    audio: 1,
    visual: 0,
    text: 0,
    price: 0,
    baseFactor: 3,
  },
  เว็บเพจ: {
    name: 'เว็บเพจ',
    audio: 0,
    visual: 1,
    text: 1,
    price: 0,
    baseFactor: 5,
  },
  โทรทัศน์: {
    name: 'โทรทัศน์',
    audio: 1,
    visual: 1,
    text: 0,
    price: 300,
    baseFactor: 12,
  },
  วิทยุ: {
    name: 'วิทยุ',
    audio: 1,
    visual: 0,
    text: 0,
    price: 150,
    baseFactor: 5,
  },
  สิ่งพิมพ์: {
    name: 'สิ่งพิมพ์',
    audio: 0,
    visual: 1,
    text: 1,
    price: 0,
    baseFactor: 8,
  },
  สื่อนอกบ้าน: {
    name: 'สื่อนอกบ้าน',
    audio: 0,
    visual: 1,
    text: 1,
    price: 250,
    baseFactor: 10,
  },
}
